version: '2.1'

services:
  comunitas-chatbot:
    image: comunitas-chatbot
    build: .
    environment:
      NODE_ENV: development
    ports:
      - 2400:2400
      - 9229:9229
    command: node --inspect=0.0.0.0:9229 index.js